export interface EmailTemplate {
  PK: string; // Template
  id: string;
  name: string;
  subject?: string;
  template?: string;
  createdBy?: string; // who created the client
  createdDate?: string;
  lastModifiedDate?: string; // auto-generated by backend
}

export interface EmailServiceRequest {
  subject: string; // Email Subject
  sender: string; // Sender email
  receivers: string[]; // Receiver emails
  replyTo?: string[]; // Reply-to emails
  ccTo?: string[]; // cc emails
  content: string; // Content of email (HTML supported)
}

export interface TemplatesPagedPayload {
  items: EmailTemplate[];
  count: number;
  scannedCount: number;
  lastEvaluatedKey: EmailTemplate;
}
