export interface Settings {
  PK: string; // Settings
  id: string;
  name: string;
  value: string;
  createdBy?: string; // who updated the setting
  createdDate?: string;
  lastModifiedDate?: string; // auto-generated by backend
}

export enum DEFAULT_SETTINGS {
  RMBCurrency = "RMBcurrency",
  ClientsPageSize = "clientsPageSize",
  PriceUnit = "priceUnit",
}
