name: Build
on:
  push:
    branches:
      - "!prod"

  pull_request:

  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VITE_APP_GMAP_API_KEY: ${{ secrets.VITE_APP_GMAP_API_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_REGION: ap-southeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make build
